size = 1280, 720

USE_PROMPTS = False
USE_OPENAI = False
DETECT_FACES = True
noise_glitching = False

NUM_SMMRY_SENTENCES = 8
MINIMUM_ARTICLE_LENGTH = 10000

GLITCH_VIDEOS = False
GLITCH_VIDEOS_PERCENT = 0.3
USE_MOVIEPY_VIDEO_FX = True
MOVIEPY_VIDEO_FX_PERCENT = 0.7

DEFAULT_IMAGES_PER_SEARCH = 4

CLEANUP_ON_FINISH = True